language: java
jdk:
 - openjdk7
 - oraclejdk7
before_install:
  # Download and setup Android toolks
  - wget http://dl.google.com/android/android-sdk_r21.0.1-linux.tgz
  - tar xzf android-sdk_r21.0.1-linux.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  # Update proper Android SDKs
  - android update sdk --filter platform-tools,android-16,extra-android-support,android-17 --no-ui --force
  - sudo apt-get update
  - sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch
  # Download and install Gradle
  - echo 'yes' | sudo add-apt-repository ppa:cwchien/gradle
  - sudo apt-get update
  - sudo apt-get install -y gradle-1.10
  # Actual build
  - /usr/lib/gradle/1.10/bin/gradle assemble --debug
