language: java
jdk:
 - openjdk7
 - oraclejdk7
before_install:
  - echo 'yes' | sudo add-apt-repository ppa:cwchien/gradle
  - sudo apt-get update
  - sudo apt-get install -y gradle
  - gradle wrapper
  - gradle assemble
